export const USER_API_ENDPOINT = import.meta.env.VITE.VITE_USER_API_ENDPOINT
export const JOB_API_ENDPOINT = import.meta.env.VITE.VITE_JOB_API_ENDPOINT
export const APPLICATION_API_ENDPOINT = import.meta.env.VITE.VITE_APPLICATION_API_ENDPOINT
export const COMPANY_API_ENDPOINT = import.meta.env.VITE.VITE_COMPANY_API_ENDPOINT
export const REGISTER_COMPANY_API_ENDPOINT = import.meta.env.VITE.VITE_REGISTER_COMPANY_API_ENDPOINT